application: shorten-url 
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /imgs
  static_dir: imgs

- url: /scripts
  static_dir: scripts

- url: /.*
  script: controller.py

