application: shorten-url 
version: 4
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /imgs
  static_dir: imgs

- url: /favicon\.ico
  static_files: imgs/favicon.ico
  upload: imgs/favicon\.ico

- url: /scripts
  static_dir: scripts

- url: /.*
  script: controller.py

