application: urlshortener
version: 1
runtime: python
api_version: 1

handlers:
- url: /css/default.css
  static_files: css/default.css
  upload: css/default.css

- url: /imgs/favicon.png
  static_files: imgs/favicon.png
  upload: imgs/favicon.png

- url: /.*
  script: controller.py

